[versions]
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
junitPlatformLauncher= "6.0.0"
jupiter = "6.0.1"
kotlin = "2.3.0"
mockk = "1.14.7"
kover = "0.9.4"
ktlint = "14.0.1"
remoteRobot = "0.11.23"
taskinfo = "3.0.1"
testLogger = "4.0.0"
versionPlugin = "0.53.0"
versionUpdate = "1.0.1"

[libraries]
jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
remoteRobot = { module = "com.intellij.remoterobot:remote-robot", version.ref = "remoteRobot" }
remoteRobotFixtures = { module = "com.intellij.remoterobot:remote-fixtures", version.ref = "remoteRobot" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
taskinfo = { id = "org.barfuin.gradle.taskinfo", version.ref = "taskinfo" }
testLogger = { id = "com.adarshr.test-logger", version.ref = "testLogger" }
versionPlugin = { id = "com.github.ben-manes.versions", version.ref = "versionPlugin" }
versionUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionUpdate" }
