name: Auto-merge
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    name: ğŸ¤ Auto-merge
    runs-on: ubuntu-latest
    if: github.actor == 'gaborbernat' || github.actor == 'dependabot[bot]' || github.actor == 'pre-commit-ci[bot]' || github.actor == 'github-actions[bot]'
    steps:
      - name: ğŸ”€ Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
